#!/usr/bin/env bash
# provision-vultr-os.sh — provision Vultr Object Storage subscription + buckets
# for the Jarvis Network stack. Idempotent: re-running on an existing
# subscription detects and reuses it.
#
# Usage:
#   VULTR_API_KEY=... ./scripts/provision-vultr-os.sh
#   # OR
#   ./scripts/provision-vultr-os.sh /path/to/vultr-api-key.txt
#
# Output: writes credentials to ${OUT_FILE:-~/.config/jarvis/vultr-os-credentials.env}
# with mode 0600. This file contains:
#   VULTR_OS_HOSTNAME=...
#   VULTR_OS_ACCESS_KEY=...
#   VULTR_OS_SECRET_KEY=...
#   VULTR_OS_SUBSCRIPTION_ID=...
#   VULTR_OS_REGION=atl

set -euo pipefail

API="https://api.vultr.com/v2"
REGION="${REGION:-atl}"
LABEL="${LABEL:-jarvis-network}"
BUCKETS=(jarvis-models jarvis-configs jarvis-backups)
OUT_FILE="${OUT_FILE:-$HOME/.config/jarvis/vultr-os-credentials.env}"

# ── resolve API key ──────────────────────────────────────────────────────────
if [ -z "${VULTR_API_KEY:-}" ] && [ -n "${1:-}" ] && [ -f "$1" ]; then
  VULTR_API_KEY="$(tr -d '[:space:]' < "$1")"
fi
if [ -z "${VULTR_API_KEY:-}" ]; then
  echo "ERROR: Set VULTR_API_KEY env var or pass a path to a file containing the key." >&2
  echo "Generate one at https://my.vultr.com/settings/#settingsapi" >&2
  exit 1
fi

curl_v() { curl -fsS -H "Authorization: Bearer ${VULTR_API_KEY}" "$@"; }

step() { printf "\033[36m→\033[0m %s\n" "$*"; }
ok()   { printf "\033[32m✓\033[0m %s\n" "$*"; }
err()  { printf "\033[31m✗\033[0m %s\n" "$*" >&2; }

# ── ensure jq + boto3 ────────────────────────────────────────────────────────
command -v jq >/dev/null 2>&1 || { err "jq is required: apt install jq"; exit 1; }
python3 -c 'import boto3' 2>/dev/null || {
  step "Installing boto3 in a venv at ~/.venvs/jarvis-os"
  python3 -m venv "$HOME/.venvs/jarvis-os"
  "$HOME/.venvs/jarvis-os/bin/pip" install --quiet boto3
  PYTHON_S3="$HOME/.venvs/jarvis-os/bin/python3"
  ok "boto3 venv ready"
}
PYTHON_S3="${PYTHON_S3:-python3}"

# ── 1. find ATL cluster id ───────────────────────────────────────────────────
step "Querying Vultr Object Storage clusters"
clusters_json=$(curl_v "${API}/object-storage/clusters")
cluster_id=$(echo "$clusters_json" | jq -r --arg r "$REGION" '
  .clusters[] | select(.region == $r) | .id' | head -1)
if [ -z "$cluster_id" ] || [ "$cluster_id" = "null" ]; then
  err "No Object Storage cluster found in region '$REGION'"
  echo "$clusters_json" | jq '.clusters[] | {id, region, hostname}' >&2
  exit 1
fi
hostname_atl=$(echo "$clusters_json" | jq -r --arg r "$REGION" '
  .clusters[] | select(.region == $r) | .hostname' | head -1)
ok "ATL cluster: id=$cluster_id hostname=$hostname_atl"

# ── 2. find or create subscription ───────────────────────────────────────────
step "Looking for existing subscription labeled '$LABEL' in $REGION"
subs_json=$(curl_v "${API}/object-storage")
sub_id=$(echo "$subs_json" | jq -r --arg l "$LABEL" --arg c "$cluster_id" '
  .object_storages[] | select(.label == $l and (.cluster_id|tostring) == $c) | .id' | head -1)

if [ -n "$sub_id" ] && [ "$sub_id" != "null" ]; then
  ok "Found existing subscription: $sub_id"
else
  step "Creating new subscription (this can take ~30s to provision)"
  create_json=$(curl_v -X POST "${API}/object-storage" \
    -H "Content-Type: application/json" \
    -d "$(jq -n --arg c "$cluster_id" --arg l "$LABEL" \
      '{cluster_id:($c|tonumber), label:$l}')")
  sub_id=$(echo "$create_json" | jq -r '.object_storage.id')
  if [ -z "$sub_id" ] || [ "$sub_id" = "null" ]; then
    err "Subscription creation failed"; echo "$create_json" | jq >&2; exit 1
  fi
  ok "Created subscription: $sub_id"

  step "Waiting for subscription to become active"
  for i in $(seq 1 60); do
    sleep 5
    status=$(curl_v "${API}/object-storage/$sub_id" | jq -r '.object_storage.status')
    if [ "$status" = "active" ]; then ok "Active after ${i}×5s"; break; fi
    [ $i -eq 60 ] && { err "Timeout waiting for active state (5min)"; exit 1; }
  done
fi

# ── 3. fetch S3 credentials ──────────────────────────────────────────────────
step "Fetching S3 credentials"
detail=$(curl_v "${API}/object-storage/$sub_id")
s3_hostname=$(echo "$detail" | jq -r '.object_storage.s3_hostname')
s3_access=$(echo   "$detail" | jq -r '.object_storage.s3_access_key')
s3_secret=$(echo   "$detail" | jq -r '.object_storage.s3_secret_key')
ok "Endpoint: https://$s3_hostname"

# ── 4. write credentials file (0600) ─────────────────────────────────────────
mkdir -p "$(dirname "$OUT_FILE")"
umask 077
cat > "$OUT_FILE" <<EOF
# Vultr Object Storage credentials for jarvis-network. Generated by
# scripts/provision-vultr-os.sh on $(date -Iseconds).
# DO NOT COMMIT.
VULTR_OS_HOSTNAME=$s3_hostname
VULTR_OS_ACCESS_KEY=$s3_access
VULTR_OS_SECRET_KEY=$s3_secret
VULTR_OS_SUBSCRIPTION_ID=$sub_id
VULTR_OS_REGION=$REGION
EOF
chmod 600 "$OUT_FILE"
ok "Wrote $OUT_FILE (mode 600)"

# ── 5. create buckets via S3 API ─────────────────────────────────────────────
step "Creating buckets: ${BUCKETS[*]}"
"$PYTHON_S3" - <<PY
import boto3
from botocore.exceptions import ClientError
s3 = boto3.client(
    "s3",
    endpoint_url=f"https://${s3_hostname}",
    aws_access_key_id="${s3_access}",
    aws_secret_access_key="${s3_secret}",
    region_name="${REGION}",
)
for b in ${BUCKETS[@]@J}:
    try:
        s3.create_bucket(Bucket=b)
        print(f"  ✓ created: {b}")
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "")
        if code in ("BucketAlreadyOwnedByYou", "BucketAlreadyExists"):
            print(f"  ✓ exists:  {b}")
        else:
            print(f"  ✗ {b}: {e}")
            raise
PY

ok "Done. Buckets ready at https://$s3_hostname"
echo
echo "Next: source $OUT_FILE && ./scripts/seed-models.py --all"
